[package]
name = "starkbot-daemon"
version = "0.1.11"
edition = "2021"

[[bin]]
name = "starkbot-daemon"
path = "src/main.rs"

[dependencies]
starkbot-api = { path = "../starkbot-api" }
tokio = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
dotenvy = { workspace = true }
anyhow = { workspace = true }
